name: altashop
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.5.0
      with:
        testFilePath: MiniProjectmantap.jmx
        outputReportsFolder: reports/
  update:
    name: Terdapat update rating pada Api 
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Run JMeter Tests Cuz Update ke 1
      - uses: actions/checkout@v3
        with:
          testFilePath: MiniProjectmantap.jmx
          outputReportsFolder: reports/
  # test:
  #    runs-on: ubuntu-latest
  #    steps:
  #     - uses: actions/checkout@v3
  #     - name: Run install JQ
  #       run: sudo apt install -y jq
  #     - name: Run get all contacts
  #       run: curl https://my-json-server.typicode.com/hadihammurabi/flutter-webservice/contacts/1 >> output.json
  #     - name: Run extract JSON
  #       run: |
  #         id=$(jq '.id' output.json)
  #         if [[ $id -eq 1 ]]
  #         then
  #           echo ok
  #         else
  #           echo fail
  #         fi
